### ISSUE TITLE
Adding an end time?

### ISSUE THREAD

**Issue by Hackmodford** [PaulWoitaschek/ChapterReader#1]
What do you think about adding a chapter end time to the returned results? Would that be a worthy addition?

For example, my old method was to have my chapter parser actually return a chapter object. The chapter object would have these properties.

Title
StartTime
EndTime

Update:
So far so good. The library seems to be working fine. I just need the end timestamps for everything to be 100% compatible. Thanks for separating this out in the first place!

**Comment by PaulWoitaschek** [comment]
I restructured some things in the latest release, check it out.

For the end time: This is not so trivial as it would require knowing the duration of the file and parsing that is an additional thing I actually don't need.

For example the chpl atom in mp4 contains (afaik) only it's start position. So in that case end of the last chapter could not be determined.
Feel free to create a pull request if you can add this features.

**Comment by Hackmodford** [comment]
Interesting, I thought they stored the end time. But even an app like this only lets you set the start time.

http://chaptersapp.com

I’ll just loop through and add the end times by looking at the next chapters start time.

**Comment by PaulWoitaschek** [comment]
You can do that but that's not an option here as that assumption cannot be made from the library. The last chapter has no succeeding chapter, that's why I was talking about the duration.

**Comment by Hackmodford** [comment]
Agreed. My app keeps track of duration so it won’t be an issue for me.

**Comment by PaulWoitaschek** [comment]
Same with voice :)
