### ISSUE TITLE
Using the library in Java

### ISSUE THREAD

**Issue by Hackmodford** [PaulWoitaschek/ChapterReader#2]
Just wanted to make sure I'm doing this correctly. Is this how I should be creating the chapter reader object?

My project is still using Java and the factory method create() didn't seem to work for me.

`ChapterReader chapterReader = DaggerChapterReaderComponent.builder().build().chapterReader();`

**Comment by PaulWoitaschek** [comment]
Absolutely not. That's an implementation detail you should not see. What do you mean by "didn't seem to work"?

**Comment by PaulWoitaschek** [comment]
I marked it as JvmStatic.
So before from java you had to call:

`ChapterReaderFactory.INSTANCE.create()` whereas now a `ChapterReaderFactory.create()` suffices.
