### ISSUE TITLE
Incorrect start time

### ISSUE THREAD

**Issue by Hackmodford** [PaulWoitaschek/ChapterReader#4]
I have an m4b file that is returning 2105120(ms) as the start time where it should be 3508533(ms).

Any suggestions on how to debug this?

update:

I checked another file and got another incorrect time.

799271 and it should be 1332118

Interesting that both are off by a factor of approximately 1.6666
For example:
2105120 * 1.6666 is approximately 3508533
799271 * 1.6666 is approximately 1332118

**Comment by PaulWoitaschek** [comment]
Send them to me please

**Comment by Hackmodford** [comment]
I will be sending a private email with the files shortly.
Thanks for the help!

**Comment by PaulWoitaschek** [comment]
Fixed in the just released 0.1.3.
